include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    missing_required_param: error
    unused_import: warning
    unused_local_variable: warning

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"

linter:
  rules:
    require_trailing_commas: true
    file_names: true
    camel_case_types: true
    non_constant_identifier_names: true
    always_declare_return_types: true
    prefer_final_fields: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true
    always_require_non_null_named_parameters: true
    avoid_null_checks_in_equality_operators: true

