targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        generate_for:
          - lib/**
      freezed:freezed:
        enabled: true
      json_serializable:json_serializable:
        enabled: true
      auto_route_generator:autoRouteGenerator:
        enabled: true

