name: chauffeur
repository: https://github.com/your-org/chauffeur

packages:
  - .

scripts:
  bootstrap:
    description: Install dependencies for all packages
    run: fvm dart pub get --no-example

  clean:
    description: Clean all packages
    run: fvm flutter clean

  format:
    description: Format all packages
    run: fvm dart format .

  analyze:
    description: Analyze all packages
    run: fvm dart analyze .

  build_runner:
    description: Run build_runner for code generation
    run: fvm dart run build_runner build --delete-conflicting-outputs

  gen_l10n:
    description: Generate localization files
    run: fvm flutter gen-l10n

