name: app_widget
description: Shared UI widgets for flutter_app
publish_to: 'none'
version: 0.0.1

# Inherit dependency versions from root pubspec.yaml
resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.38.8 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: any
  get_it: any
  injectable: any
  freezed_annotation: any
  auto_route: any
  bloc: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  injectable_generator: any
  freezed_annotation_generator: any
  auto_route_generator: any
  bloc_generator:
