name: use_cases
description: Application layer containing business logic (use cases) for flutter_app
publish_to: 'none'
version: 0.0.1

# Inherit dependency versions from root pubspec.yaml
resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  # Internal Packages
  domain: any
  app_core: any

  # Dependency Injection
  get_it: any
  injectable: any

  # Code Generation
  freezed_annotation: any
  json_annotation: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  
  # Code Generation
  build_runner: any
  freezed: any
  json_serializable: any
  injectable_generator: any
