name: app_core
description: Shared core configuration
publish_to: 'none'
version: 0.0.1

# Inherit dependency versions from root pubspec.yaml
resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.38.8 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Dependency Injection
  get_it: any
  injectable: any
  
  # Services
  connectivity_plus: any
  permission_handler: any
  auto_route: any
  
  # Code Generation
  freezed_annotation: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  injectable_generator: any
  freezed: any