targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        generate_for:
          include:
            - lib/**/*.dart
          exclude:
            - lib/l10n/**
      auto_route_generator:auto_route_generator:
        enabled: true
        options:
          enable_cached_builds: true
