name: domain
description: Domain layer containing entities, use cases, and repository interfaces for flutter_app
publish_to: 'none'
version: 0.0.1

resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  # Code Generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  freezed: ^3.2.4
  json_serializable: ^6.8.0
