name: flutter_app
description: A Flutter application following Clean Architecture principles
publish_to: 'none'
version: 1.0.0+1

resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.38.8 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: any
  bloc_event_transformers: any

  # Dependency Injection
  get_it: any
  injectable: any

  # Code Generation
  freezed_annotation: any
  json_annotation: any
  auto_route: any

  # Networking
  dio: any
  retrofit: any

  # Local Storage
  shared_preferences: any

  # Network Connectivity
  connectivity_plus: any

  # Permissions
  permission_handler: any

  # Internal Packages
  data: any
  app_utility: any
  app_widget: any
  app_core: any
  domain: any
  use_cases: any
  feature_auth: any
  feature_app_settings: any
  fluttertoast: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

  # Code Generation
  build_runner: any
  freezed: any
  json_serializable: any
  injectable_generator: any
  auto_route_generator: any
  retrofit_generator: any

flutter:
  uses-material-design: true
  generate: true

  # assets:
  #   - assets/icon/
  #   - assets/image/
  #   - assets/animation/
  #   - assets/image/bank/

  # fonts:
  #   - family: Pretendard
  #     fonts:
  #       - asset: assets/fonts/Pretendard-Regular.otf
  #       - asset: assets/fonts/Pretendard-Bold.otf
  #         weight: 700

flutter_gen:
  line_length: 250
  output: lib/assets/

  assets:
    outputs:
      package_parameter_enabled: false
      class_name: AppAsset
  integrations:
    flutter_svg: true
    lottie: true
